"""Initial ZentWHook schema
Revision ID: a11559d361ea
Revises: 
Create Date: 2026-09-06 07:40:20.843274
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'a11559d361ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('auth_type', sa.String(length=40), nullable=False),
    sa.Column('auth_username', sa.String(length=255), nullable=False),
    sa.Column('auth_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('auth_header_name', sa.String(length=120), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('retry_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_delays', sa.JSON(), nullable=False),
    sa.Column('retry_exponential', sa.Boolean(), nullable=False),
    sa.Column('retry_statuses', sa.JSON(), nullable=False),
    sa.Column('allow_private', sa.Boolean(), nullable=False),
    sa.Column('allow_localhost', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.create_table('incoming_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('methods', sa.JSON(), nullable=False),
    sa.Column('content_types', sa.JSON(), nullable=False),
    sa.Column('max_payload_bytes', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('request_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('ip_allowlist', sa.JSON(), nullable=False),
    sa.Column('ip_denylist', sa.JSON(), nullable=False),
    sa.Column('synchronous', sa.Boolean(), nullable=False),
    sa.Column('retention_success_days', sa.Integer(), nullable=True),
    sa.Column('retention_failed_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoming_endpoints_name'), 'incoming_endpoints', ['name'], unique=False)
    op.create_index(op.f('ix_incoming_endpoints_slug'), 'incoming_endpoints', ['slug'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index('ix_jobs_ready', 'jobs', ['status', 'run_at'], unique=False)
    op.create_index(op.f('ix_jobs_run_at'), 'jobs', ['run_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('endpoint_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('auth_type', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('header_name', sa.String(length=120), nullable=False),
    sa.Column('hmac_algorithm', sa.String(length=20), nullable=False),
    sa.Column('hmac_payload_basis', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['incoming_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('replay_of_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('body_encrypted', sa.Text(), nullable=False),
    sa.Column('body_masked', sa.Text(), nullable=False),
    sa.Column('body_size', sa.Integer(), nullable=False),
    sa.Column('query_encrypted', sa.Text(), nullable=False),
    sa.Column('query_masked', sa.JSON(), nullable=False),
    sa.Column('auth_ok', sa.Boolean(), nullable=False),
    sa.Column('auth_message', sa.String(length=255), nullable=False),
    sa.Column('processing_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processing_trace', sa.JSON(), nullable=False),
    sa.Column('search_blob', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['incoming_endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replay_of_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_endpoint_id'), 'events', ['endpoint_id'], unique=False)
    op.create_index('ix_events_endpoint_received', 'events', ['endpoint_id', 'received_at'], unique=False)
    op.create_index(op.f('ix_events_received_at'), 'events', ['received_at'], unique=False)
    op.create_index(op.f('ix_events_request_id'), 'events', ['request_id'], unique=True)
    op.create_index(op.f('ix_events_source_ip'), 'events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index('ix_events_status_received', 'events', ['status', 'received_at'], unique=False)
    op.create_table('flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('condition_logic', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['incoming_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flows_endpoint_id'), 'flows', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_flows_name'), 'flows', ['name'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_request_encrypted', sa.Text(), nullable=False),
    sa.Column('final_request_masked', sa.Text(), nullable=False),
    sa.Column('response_encrypted', sa.Text(), nullable=False),
    sa.Column('response_masked', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'flow_id', 'destination_id', name='uq_delivery_route')
    )
    op.create_index(op.f('ix_deliveries_created_at'), 'deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_deliveries_destination_id'), 'deliveries', ['destination_id'], unique=False)
    op.create_index('ix_deliveries_event_created', 'deliveries', ['event_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_deliveries_event_id'), 'deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_deliveries_http_status'), 'deliveries', ['http_status'], unique=False)
    op.create_index(op.f('ix_deliveries_next_retry_at'), 'deliveries', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.create_index('ix_deliveries_status_retry', 'deliveries', ['status', 'next_retry_at'], unique=False)
    op.create_table('event_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('masked_value', sa.Text(), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_headers_event_id'), 'event_headers', ['event_id'], unique=False)
    op.create_table('flow_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_destinations_destination_id'), 'flow_destinations', ['destination_id'], unique=False)
    op.create_index(op.f('ix_flow_destinations_flow_id'), 'flow_destinations', ['flow_id'], unique=False)
    op.create_table('flow_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(length=300), nullable=False),
    sa.Column('operator', sa.String(length=40), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_rules_flow_id'), 'flow_rules', ['flow_id'], unique=False)
    op.create_table('mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_path', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_value', sa.Text(), nullable=False),
    sa.Column('static_type', sa.String(length=30), nullable=False),
    sa.Column('fallback_json', sa.JSON(), nullable=True),
    sa.Column('transforms', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mappings_flow_id'), 'mappings', ['flow_id'], unique=False)
    op.create_table('delivery_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_attempts_delivery_id'), 'delivery_attempts', ['delivery_id'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_attempts_delivery_id'), table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    op.drop_index(op.f('ix_mappings_flow_id'), table_name='mappings')
    op.drop_table('mappings')
    op.drop_index(op.f('ix_flow_rules_flow_id'), table_name='flow_rules')
    op.drop_table('flow_rules')
    op.drop_index(op.f('ix_flow_destinations_flow_id'), table_name='flow_destinations')
    op.drop_index(op.f('ix_flow_destinations_destination_id'), table_name='flow_destinations')
    op.drop_table('flow_destinations')
    op.drop_index(op.f('ix_event_headers_event_id'), table_name='event_headers')
    op.drop_table('event_headers')
    op.drop_index('ix_deliveries_status_retry', table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_next_retry_at'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_http_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_event_id'), table_name='deliveries')
    op.drop_index('ix_deliveries_event_created', table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_destination_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_created_at'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_flows_name'), table_name='flows')
    op.drop_index(op.f('ix_flows_endpoint_id'), table_name='flows')
    op.drop_table('flows')
    op.drop_index('ix_events_status_received', table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_source_ip'), table_name='events')
    op.drop_index(op.f('ix_events_request_id'), table_name='events')
    op.drop_index(op.f('ix_events_received_at'), table_name='events')
    op.drop_index('ix_events_endpoint_received', table_name='events')
    op.drop_index(op.f('ix_events_endpoint_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('endpoint_auth')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_at'), table_name='jobs')
    op.drop_index('ix_jobs_ready', table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_incoming_endpoints_slug'), table_name='incoming_endpoints')
    op.drop_index(op.f('ix_incoming_endpoints_name'), table_name='incoming_endpoints')
    op.drop_table('incoming_endpoints')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
